spring:
  application:
    name: jobportal
  datasource:
    url: jdbc:postgresql://localhost:5434/jobportal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jackson:
    default-property-inclusion: non-null
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
